KTB-02 create file
ArtemMrtN/KotlinTelegramBot pull request #1
Opened 2024-11-12 06:52 UTC by ArtemMrtN

2024-11-12 09:52 UTC, dzenonce approved these changes

2024-11-12 09:52 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +    val allWords = wordsFile.readLines()
Здесь можно использовать `forEachLine {}` - это будет еще короче.

2024-11-12 11:28 UTC, ArtemMrtN commented on src/main/kotlin/Main.kt
> +    val allWords = wordsFile.readLines()
Понял, спасибо. Поменял

2024-11-12 19:06 UTC, dzenonce requested changes
Все здорово, только давай на каждую задачу создавать свой pr

2024-11-12 19:06 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +    var correctAnswersCount: Int? = 0
Вот здесь лучше убрать нулябельность, нам достаточно значения по умолчанию 0, иначе в будущем могут быть некоторые сложности с нулябельностью здесь

2024-11-13 05:38 UTC, ArtemMrtN commented on src/main/kotlin/Main.kt
> +    var correctAnswersCount: Int? = 0
Нулябельность убрал. Мне показалось это IDEA сама предложила. Странно.

Про свой PR я уже как отправил на проверку, то вспомнил, что надо было новый создать. А заново отправить нельзя было. Следующий раз сделаю новый обязательно.

2024-11-13 18:01 UTC, dzenonce approved these changes

2024-11-14 04:08 UTC, merged