KTB-15 send message
ArtemMrtN/KotlinTelegramBot pull request #11
Opened 2024-11-22 07:56 UTC by ArtemMrtN

2024-11-22 17:00 UTC, dzenonce requested changes

2024-11-22 17:00 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val urlUpdates = "https://api.telegram.org/bot$botToken/getUpdates?offset=$updateId"
`https://api.telegram.org/bot` - можно вынести в константы

2024-11-22 17:00 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val client: HttpClient = HttpClient.newBuilder().build()
HttpClient можно сделать полем TelegramBotService, чтобы не создавать экземпляр при каждом сетевом вызове.

2024-11-22 17:00 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +    fun getUpdates(botToken: String, updateId: Int): String {
botToken можно передать в конструктор TelegramBotService, чтобы не прокидывать в каждый метод

2024-11-22 17:00 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +class TelegramBotService {
Давай этот класс вынесем в отдельный файл и назовем его `TelegramBotService`

2024-11-23 13:57 UTC, dzenonce requested changes

2024-11-23 13:57 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +class TelegramBotService(args: Array<String>) {
Немного не так, здесь нужно передавать только токен, а не массив аргументов, которые могут передаваться через консоль, т.е нужно оставить получение токена в main и здесь получать только строку с токеном

2024-11-23 14:44 UTC, ArtemMrtN commented on src/main/kotlin/TelegramBotService.kt
> +class TelegramBotService(args: Array<String>) {
Надеюсь правильно понял)

2024-11-24 12:16 UTC, dzenonce approved these changes
Да, теперь все верно!

2024-11-25 06:13 UTC, merged