KTB-16 buttons
ArtemMrtN/KotlinTelegramBot pull request #12
Opened 2024-11-25 08:13 UTC by ArtemMrtN

2024-11-25 18:55 UTC, dzenonce requested changes

2024-11-25 18:55 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +                            "callback_data": "learn_words_clicked"
Давай вынесем `"learn_words_clicked"`  в константы `"statistics_clicked"` из тела `sendMenuBody`

2024-11-25 18:55 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +    fun sendMenu(chatId: Int): String {
При приведении к типу int при отправке меню, id пользователя выходит из диапазона int и поэтому приложение падает с ошибкой, чтобы этого избежать, можно передавать просто строкой число или приводить к типу Long

2024-11-25 18:55 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val chatId = chatIdRegex.find(updates)?.groups?.get(2)?.value?.toInt()
А давай здесь зделаем более устойчиво, к тому же не всегда может прийти chatId - `toIntOrNull() ?: continue`

2024-11-26 06:21 UTC, ArtemMrtN commented on src/main/kotlin/Telegram.kt
> +        val chatId = chatIdRegex.find(updates)?.groups?.get(2)?.value?.toInt()
Но получается, если я chatId сделал теперь как String, то это уже не актуально?

2024-11-26 19:26 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val chatId = chatIdRegex.find(updates)?.groups?.get(2)?.value?.toInt()
Тебе все равно необходимо делать continue если пришел null от сервера вместо chatId

2024-11-26 19:30 UTC, dzenonce requested changes

2024-11-26 19:30 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val chatId = chatIdRegex.find(updates)?.groups?.get(2)?.value
Все же если chatId с сервера пришел null необходимо делать continue, т.к программа и не может продолжать работу

2024-11-27 20:02 UTC, dzenonce approved these changes
Хорошо

2024-11-28 05:32 UTC, merged