KTB-19 Process responses
ArtemMrtN/KotlinTelegramBot pull request #15
Opened 2024-12-02 06:18 UTC by ArtemMrtN

2024-12-02 18:40 UTC, dzenonce requested changes

2024-12-02 18:40 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        if (data?.startsWith(CALLBACK_DATA_ANSWER_PREFIX, true) == true) {
Можно чуть компактнее:
`data?.startsWith(CALLBACK_DATA_ANSWER_PREFIX) == true`

2024-12-02 18:40 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +            val userAnswerIndex = data.substringAfter("answer_").toInt()
Префикс лучше вынести в константу

2024-12-02 18:40 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +                Thread.sleep(1000)
А для чего ты усыпляешь поток?

2024-12-03 03:57 UTC, ArtemMrtN commented on src/main/kotlin/Telegram.kt
> +            val userAnswerIndex = data.substringAfter("answer_").toInt()
Затупил) Константу же создал, а тут не прописал.

2024-12-03 03:58 UTC, ArtemMrtN commented on src/main/kotlin/Telegram.kt
> +                Thread.sleep(1000)
Чтобы сообщения в боте появлялись не разом два, а с паузой. Как мне кажется, так выглядит более естественно. Или так не делают?

2024-12-03 17:35 UTC, dzenonce approved these changes

2024-12-03 17:35 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +                Thread.sleep(1000)
Как правило нет

2024-12-04 04:07 UTC, merged